// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksApi.Data;

#nullable disable

namespace NZWalksApi.Migrations
{
    [DbContext(typeof(NZWalksDbContextcs))]
    [Migration("20250428214518_Seeding Data for Difficulties and Region")]
    partial class SeedingDataforDifficultiesandRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksApi.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            id = new Guid("752f441b-3268-4729-845a-02df3c0e7e13"),
                            Name = "Facil"
                        },
                        new
                        {
                            id = new Guid("55a87c60-33b4-4bcf-96a8-76c644dd7e20"),
                            Name = "Normal"
                        },
                        new
                        {
                            id = new Guid("284a9d17-9e07-4796-a0c8-199cb2ebd637"),
                            Name = "Dificil"
                        });
                });

            modelBuilder.Entity("NZWalksApi.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f4eacfc-eaab-4cde-b87d-2b4544b8a84a"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImagenUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.pngtree.com%2Ffree-backgrounds-photos%2Ffotos-anchas-pictures&psig=AOvVaw18mVrfLuAspgyKVvaKJG9A&ust=1745962585637000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDtstPX-4wDFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("470b646a-063e-4a94-8346-f50135212f6d"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImagenUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.pngtree.com%2Ffree-backgrounds-photos%2Ffotos-anchas-pictures&psig=AOvVaw18mVrfLuAspgyKVvaKJG9A&ust=1745962585637000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDtstPX-4wDFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("e5973695-f958-41d3-8b68-8ec2d89cb159"),
                            Code = "MSN",
                            Name = "Nelson",
                            RegionImagenUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.pngtree.com%2Ffree-backgrounds-photos%2Ffotos-anchas-pictures&psig=AOvVaw18mVrfLuAspgyKVvaKJG9A&ust=1745962585637000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDtstPX-4wDFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("fc6d6315-4fff-41b7-8a3b-53d0224a477d"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImagenUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.pngtree.com%2Ffree-backgrounds-photos%2Ffotos-anchas-pictures&psig=AOvVaw18mVrfLuAspgyKVvaKJG9A&ust=1745962585637000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDtstPX-4wDFQAAAAAdAAAAABAE"
                        });
                });

            modelBuilder.Entity("NZWalksApi.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("difficultyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("lengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("regionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("walkImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("difficultyid");

                    b.HasIndex("regionId");

                    b.ToTable("walks");
                });

            modelBuilder.Entity("NZWalksApi.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalksApi.Models.Domain.Difficulty", "difficulty")
                        .WithMany()
                        .HasForeignKey("difficultyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksApi.Models.Domain.Region", "region")
                        .WithMany()
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("difficulty");

                    b.Navigation("region");
                });
#pragma warning restore 612, 618
        }
    }
}
